<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DS-PC" name="Tests" tests="3" failures="0" timestamp="13 Jul 2016 09:48:10 GMT" time="134.874" errors="0">
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.ZigyCure.AddtoOrder">
    <failure type="java.lang.Exception" message="TestCases.ZigyCure.AddtoOrder : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.ZigyCure.AddtoOrder : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.ZigyCure.AddtoOrder.ExecutionStatusCheck(AddtoOrder.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="testLogin" time="64.321" classname="TestCases.ZigyCare.CareLogin"/>
  <testcase name="testAdd2Order" time="0.0" classname="TestCases.ZigyCure.AddtoOrder">
    <skipped/>
  </testcase> <!-- testAdd2Order -->
  <testcase name="testLogin" time="51.869" classname="TestCases.ZigyHealthVault.HVLogin"/>
</testsuite> <!-- Tests -->
